version: '2'

services:

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    volumes:
      - 'mysqldb_data:/var/lib/mysql'
    networks:
      default:
        aliases:
          - db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: hortonworks
      MYSQL_USER: hortonworks
      MYSQL_PASSWORD: password


  registry:
    build: .
    #image: hwx
    depends_on:
      - db
    ports:
      - "9090:9090"
      - "9091:9091"
    environment:
      DB_NAME: hortonworks
      DB_USER: hortonworks
      DB_PASSWORD: password
      DB_PORT: 3306
      DB_HOST: db


volumes:
  mysqldb_data:
    driver: local
